# Generated by Django 5.1.6 on 2025-03-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertdata',
            name='image',
            field=models.TextField(blank=True, db_index=True, help_text='картинка обнаруженного объекта', null=True),
        ),
        migrations.AlterField(
            model_name='alertdata',
            name='first_detection_datetime',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Время первого обнаружения', null=True),
        ),
        migrations.AlterField(
            model_name='alertdata',
            name='last_detection_datetime',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Время последнего обнаружения', null=True),
        ),
    ]
