# Generated by Django 5.1.6 on 2025-03-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alertdata_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alertdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
