# Generated by Django 5.1.6 on 2025-03-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_alertdata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertdata',
            options={},
        ),
        migrations.AddField(
            model_name='alertdata',
            name='number',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='номер обнаружения', null=True),
        ),
        migrations.AlterField(
            model_name='alertdata',
            name='first_detection_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertdata',
            name='image',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertdata',
            name='last_detection_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
